services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      API_KEY: ${API_KEY}
      MONGO_URI: mongodb://root:root@mongo:27017/dash?authSource=admin
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GUILD_ID: ${GUILD_ID}
      ADMIN_ROLE_ID: ${ADMIN_ROLE_ID}
      PURCHASE_LOGS_CHANNEL_ID: ${PURCHASE_LOGS_CHANNEL_ID}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/"]
      interval: 5s
      retries: 20
      start_period: 5s

  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    container_name: website
    restart: unless-stopped
    depends_on:
      - server
    environment:
      PORT: ${WEBSITE_PORT}
      APP_URL: "${WEBSITE_URL:-http://localhost:${WEBSITE_PORT}}"
      SERVER_URL: "http://server:${SERVER_PORT}/api"
      DISCORD_OAUTH_CLIENT_ID: ${DISCORD_OAUTH_CLIENT_ID}
      DISCORD_OAUTH_CLIENT_SECRET: ${DISCORD_OAUTH_CLIENT_SECRET}
      ROBLOX_OAUTH_ID: ${ROBLOX_OAUTH_ID}
      ROBLOX_OAUTH_SECRET: ${ROBLOX_OAUTH_SECRET}
    ports:
      - "${WEBSITE_PORT}:${WEBSITE_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WEBSITE_PORT}"]
      interval: 5s
      retries: 20
      start_period: 5s
  notifier:
    image: busybox:latest
    depends_on:
      server:
        condition: service_healthy
      website:
        condition: service_healthy
volumes:
  mongo_data:
